FROM prom/prometheus:v3.5.0

COPY render.yml /etc/prometheus/prometheus.yml

EXPOSE 9090
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.listen-address=0.0.0.0:${PORT:-9090}"]
